# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the FTS Capacitive touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_ST_FTS_V521)		+= fts521.o
fts521-y									:= fts.o fts_lib/ftsCore.o fts_lib/ftsError.o fts_lib/ftsFrame.o fts_lib/ftsIO.o fts_lib/ftsTime.o fts_lib/ftsTool.o
